# Generated by Django 3.1.3 on 2020-11-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201124_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.AuctionList'),
        ),
    ]
