# Generated by Django 3.1.3 on 2020-11-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201125_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
