# Generated by Django 3.1.3 on 2020-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201125_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='img_url',
            field=models.TextField(),
        ),
    ]
